import type { PrintDirection } from "./label";
import { LabelType, type PrinterModelMeta } from "@mmote/niimbluelib";

export type PaperFamily =
  | "d-series"
  | "d-series-hi"
  | "b1-b21"
  | "b31-b4"
  | "b3s"
  | "b18"
  | "n1"
  | "other";

export type PaperTemplate = {
  title: string;
  family: PaperFamily;
  widthMm: number;
  heightMm?: number;
  dpmm: number;
  printDirection: PrintDirection;
  labelType: LabelType;
  continuous?: boolean;
  shape?: "rect" | "rounded" | "circle";
};

const DPMM_203 = 8;
const DPMM_300 = 11.81;

export const PAPER_TEMPLATES: PaperTemplate[] = [
  {
    title: "D 12x22mm",
    family: "d-series",
    widthMm: 12,
    heightMm: 22,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 12x30mm",
    family: "d-series",
    widthMm: 12,
    heightMm: 30,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 12x40mm",
    family: "d-series",
    widthMm: 12,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 12x50mm",
    family: "d-series",
    widthMm: 12,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 12x75mm",
    family: "d-series",
    widthMm: 12,
    heightMm: 75,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 12x40mm round",
    family: "d-series",
    widthMm: 12,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "left",
    shape: "rounded",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 14x25mm",
    family: "d-series",
    widthMm: 14,
    heightMm: 25,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 14x30mm",
    family: "d-series",
    widthMm: 14,
    heightMm: 30,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 14x40mm",
    family: "d-series",
    widthMm: 14,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 14x50mm",
    family: "d-series",
    widthMm: 14,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 15x30mm",
    family: "d-series",
    widthMm: 15,
    heightMm: 30,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 15x50mm",
    family: "d-series",
    widthMm: 15,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 12x40mm clear",
    family: "d-series",
    widthMm: 12,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.Transparent,
  },
  {
    title: "D 15x50mm clear",
    family: "d-series",
    widthMm: 15,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.Transparent,
  },
  {
    title: "D continuous 12mm",
    family: "d-series",
    widthMm: 12,
    dpmm: DPMM_203,
    printDirection: "left",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "D continuous 15mm",
    family: "d-series",
    widthMm: 15,
    dpmm: DPMM_203,
    printDirection: "left",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "D 20x40mm (D101)",
    family: "d-series",
    widthMm: 20,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 20x50mm (D101)",
    family: "d-series",
    widthMm: 20,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 25x50mm (D101)",
    family: "d-series",
    widthMm: 25,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D 25x70mm (D101)",
    family: "d-series",
    widthMm: 25,
    heightMm: 70,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D continuous 20mm (D101)",
    family: "d-series",
    widthMm: 20,
    dpmm: DPMM_203,
    printDirection: "left",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "D-Hi 12x40mm 300dpi",
    family: "d-series-hi",
    widthMm: 12,
    heightMm: 40,
    dpmm: DPMM_300,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D-Hi 12x50mm 300dpi",
    family: "d-series-hi",
    widthMm: 12,
    heightMm: 50,
    dpmm: DPMM_300,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D-Hi 15x50mm 300dpi",
    family: "d-series-hi",
    widthMm: 15,
    heightMm: 50,
    dpmm: DPMM_300,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "D-Hi 12x40mm clear 300dpi",
    family: "d-series-hi",
    widthMm: 12,
    heightMm: 40,
    dpmm: DPMM_300,
    printDirection: "left",
    labelType: LabelType.Transparent,
  },
  {
    title: "D-Hi continuous 12mm 300dpi",
    family: "d-series-hi",
    widthMm: 12,
    dpmm: DPMM_300,
    printDirection: "left",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "B 30x15mm",
    family: "b1-b21",
    widthMm: 30,
    heightMm: 15,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 30x20mm",
    family: "b1-b21",
    widthMm: 30,
    heightMm: 20,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 40x15mm",
    family: "b1-b21",
    widthMm: 40,
    heightMm: 15,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 40x20mm",
    family: "b1-b21",
    widthMm: 40,
    heightMm: 20,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 40x30mm",
    family: "b1-b21",
    widthMm: 40,
    heightMm: 30,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 40x40mm",
    family: "b1-b21",
    widthMm: 40,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 40x60mm",
    family: "b1-b21",
    widthMm: 40,
    heightMm: 60,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 40x70mm",
    family: "b1-b21",
    widthMm: 40,
    heightMm: 70,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 42x21mm",
    family: "b1-b21",
    widthMm: 42,
    heightMm: 21,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 50x30mm",
    family: "b1-b21",
    widthMm: 50,
    heightMm: 30,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 50x50mm square",
    family: "b1-b21",
    widthMm: 50,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 50x50mm round",
    family: "b1-b21",
    widthMm: 50,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "top",
    shape: "rounded",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 50x70mm",
    family: "b1-b21",
    widthMm: 50,
    heightMm: 70,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 50x80mm",
    family: "b1-b21",
    widthMm: 50,
    heightMm: 80,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 40x30mm clear",
    family: "b1-b21",
    widthMm: 40,
    heightMm: 30,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.Transparent,
  },
  {
    title: "B 50x30mm clear",
    family: "b1-b21",
    widthMm: 50,
    heightMm: 30,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.Transparent,
  },
  {
    title: "B 50x50mm clear round",
    family: "b1-b21",
    widthMm: 50,
    heightMm: 50,
    dpmm: DPMM_203,
    printDirection: "top",
    shape: "rounded",
    labelType: LabelType.Transparent,
  },
  {
    title: "B continuous 40mm",
    family: "b1-b21",
    widthMm: 40,
    dpmm: DPMM_203,
    printDirection: "top",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "B continuous 50mm",
    family: "b1-b21",
    widthMm: 50,
    dpmm: DPMM_203,
    printDirection: "top",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "B 40x30mm 300dpi",
    family: "b1-b21",
    widthMm: 40,
    heightMm: 30,
    dpmm: DPMM_300,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B 50x30mm 300dpi",
    family: "b1-b21",
    widthMm: 50,
    heightMm: 30,
    dpmm: DPMM_300,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B3S 70x40mm",
    family: "b3s",
    widthMm: 70,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B3S continuous 70mm",
    family: "b3s",
    widthMm: 70,
    dpmm: DPMM_203,
    printDirection: "top",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "B31 70x100mm",
    family: "b31-b4",
    widthMm: 70,
    heightMm: 100,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B31 90x100mm",
    family: "b31-b4",
    widthMm: 90,
    heightMm: 100,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B31 continuous 70mm",
    family: "b31-b4",
    widthMm: 70,
    dpmm: DPMM_203,
    printDirection: "top",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "B31 70x100mm clear",
    family: "b31-b4",
    widthMm: 70,
    heightMm: 100,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.Transparent,
  },
  {
    title: "B4 100x150mm",
    family: "b31-b4",
    widthMm: 100,
    heightMm: 150,
    dpmm: DPMM_203,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B4 100x150mm 300dpi",
    family: "b31-b4",
    widthMm: 100,
    heightMm: 150,
    dpmm: DPMM_300,
    printDirection: "top",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B18 12x22mm",
    family: "b18",
    widthMm: 12,
    heightMm: 22,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B18 12x40mm",
    family: "b18",
    widthMm: 12,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.WithGaps,
  },
  {
    title: "B18 12x40mm clear",
    family: "b18",
    widthMm: 12,
    heightMm: 40,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.Transparent,
  },
  {
    title: "B18 continuous 12mm",
    family: "b18",
    widthMm: 12,
    dpmm: DPMM_203,
    printDirection: "left",
    continuous: true,
    labelType: LabelType.Continuous,
  },
  {
    title: "B18 heat shrink 12mm",
    family: "b18",
    widthMm: 12,
    dpmm: DPMM_203,
    printDirection: "left",
    continuous: true,
    labelType: LabelType.HeatShrinkTube,
  },
  {
    title: "N1 PET 50x80mm",
    family: "n1",
    widthMm: 50,
    heightMm: 80,
    dpmm: DPMM_203,
    printDirection: "left",
    labelType: LabelType.Transparent,
  },
  {
    title: "N1 PET continuous 50mm",
    family: "n1",
    widthMm: 50,
    dpmm: DPMM_203,
    printDirection: "left",
    continuous: true,
    labelType: LabelType.Transparent,
  },
];

export const PAPER_FAMILIES: { id: PaperFamily; label: string }[] = [
  { id: "d-series", label: "D11 / D110 / D101 / H1S" },
  { id: "d-series-hi", label: "D11-H / D11 Pro (300dpi)" },
  { id: "b1-b21", label: "B1 / B21 / B3S" },
  { id: "b3s", label: "B3S wide" },
  { id: "b31-b4", label: "B31 / B4" },
  { id: "b18", label: "B18 / B18S" },
  { id: "n1", label: "N1" },
];

export const paperFitsPrinter = (template: PaperTemplate, meta: PrinterModelMeta): boolean => {
  if (template.printDirection !== meta.printDirection) return false;
  if (!meta.paperTypes.includes(template.labelType)) return false;
  const widthPx = Math.round(template.widthMm * template.dpmm);
  if (widthPx > meta.printheadPixels) return false;
  return true;
};

export const filterTemplatesForPrinter = (
  templates: PaperTemplate[],
  meta: PrinterModelMeta | undefined,
): PaperTemplate[] => {
  if (!meta) return templates;
  const filtered = templates.filter((t) => paperFitsPrinter(t, meta));
  return filtered.length > 0 ? filtered : templates;
};
